# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
